### ISSUE TITLE
Plugin hijacks mouse right-click signal from autoTrace plugin

### ISSUE THREAD

**Issue by mostlyAtNight** [olivierdalang/CadInput#29]
Hello there,

Right-click no longer allows the user to finish digitising a polygon made using the autoTrace tool / plugin.  

CadInput seems to hijack the right-click event (it appears to do this around line 180 in CadEventFilter.py).  At present, this occurs even when the Enable CAD input button is not toggled.  

Please let me know if you'd like more information / data to reproduce and I'll be happy to send something through.  

Kind regards,

Pete

**Comment by saberraz** [comment]
Thanks!

**Comment by olivierdalang** [comment]
@saberraz It's not fixed, but this plugin is now obsolete since functionality has been added to core... Problems must now be reported on QGIS's tracker.
