### ISSUE TITLE
Distance does not coincide with Googlestreets distance

### ISSUE THREAD

**Issue by iluschevskaya** [olivierdalang/CadInput#31]
Hi, 
when trying to create line restricted by distance (e.g. 100km), it creates line which is appeared to be 100km according to CADInput, but is about 50km according to Googlestreets (it covers about half of the road drawn in Googlestreets), project is in WGS 84/ EPSG 3857. Is it really a bug or I just don't know how to use the tool appropriately?
thanks!
![cadinput_issue_1](https://cloud.githubusercontent.com/assets/11321587/6494542/93709e72-c2d3-11e4-8a5d-6cdf0886b01d.png)
![cadinput_issue_2](https://cloud.githubusercontent.com/assets/11321587/6494547/9ccd0fa0-c2d3-11e4-8131-eec98cd95298.png)

**Comment by olivierdalang** [comment]
Hi,

You have to work with a local CRS to do be able to input real measures.

By the way, CADInput has been included into core QGIS now, so questions&bugs should be asked on QGIS' mailing lists/forums/tracker from now on.

Best,

Olivier
